on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/*
      - _config.yml
      - assets/**
      - content/**
      - data/**
      - i18n/**
      - layouts/**
      - static/**

name: Site Deployment

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Build site
        run: hugo -gcc

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: scratchaddons.com
