on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/update-changelog.yml

name: Changelog Update

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScratchAddons/website-v2
        uses: actions/checkout@v2
        with:
          path: repo
      - name: Checkout ScratchAddons/website-v2-script
        uses: actions/checkout@v2
        with:
          repository: ScratchAddons/website-v2-script
          path: script
        
      - name: Update changelog
        run: |
          cd repo
          bash ../script/sh/hugo-update-changelog.sh
          
      - name: Generate token 
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
          
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update changelog
          branch: create-pull-request/changelog
          committer: scratchaddons-bot[bot] <73682299+scratchaddons-bot[bot]@users.noreply.github.com>
          delete-branch: true
          path: ./repo
          title: Update changelog
          body: |
            This updates the changelog with the main repository's version.

            It is recommended to do a rebase merge than other methods.
